### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/web-vitals#43]
Hey,

I will work on making the module work with Nuxt 3 out of the box.

**Comment by Baroshem** [comment]
The work is currently done on the `next` branch and will be released probably next week after some testing.

**Comment by andreemic** [comment]
That's awesome! How is it going? ETA?

**Comment by Baroshem** [comment]
@andreemic 

The PR is ready. Just waiting to be reviewed and merged 🙂

**Comment by maximilian-schwarz** [comment]
Any news?

**Comment by YangHanlin** [comment]
Is there any update regarding this issue and its related PR #47? According to a [comment](https://github.com/nuxt-modules/web-vitals/pull/47#issuecomment-1299994489) in the PR, the `main` branch is already working well with Nuxt 3; but it is unfortunately not true with `nuxt@3.0.0-rc.14` or later versions.

Logs of postinstall script with `nuxtjs/web-vitals@0.1.10` (latest release on `main` branch) and `nuxt@3.0.0-rc.13`:

```
home postinstall$ nuxt prepare
│ Nuxi 3.0.0-rc.13
│  WARN  [@nuxtjs/web-vitals] Please define a provider to activate this module
│  ERROR  (node:42744) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
│ (Use `node --trace-warnings ...` to show where the warning was created)
│ √ Types generated in .nuxt
└─ Done in 3.1s
```

compared with logs of postinstall script with `nuxtjs/@web-vitals@0.1.10` (latest release on `main` branch) and `nuxt@3.0.0-rc.14`:

```
home postinstall$ nuxt prepare
│ Nuxi 3.0.0-rc.14
│  ERROR  Cannot destructure property 'nuxt' of 'this' as it is undefined.
│   at webVitalsModule (D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/@nuxtjs+web-vitals@0.1.10/node_modules/@nuxtjs/web-vitals/dist/index.j
│   at installModule (/D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/@nuxt+kit@3.0.0-rc.14_rollup@2.79.1/node_modules/@nuxt/kit/dist/index.m
│   at async initNuxt (/D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/nuxt@3.0.0-rc.14_t7kkosihzizynsd35m2tpz76wa/node_modules/nuxt/dist/ind
│   at async loadNuxt (/D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/nuxt@3.0.0-rc.14_t7kkosihzizynsd35m2tpz76wa/node_modules/nuxt/dist/ind
│   at async loadNuxt (/D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/@nuxt+kit-edge@3.0.0-rc.14-27796957.b60f136_rollup@2.79.1/node_modules
│   at async Object.invoke (/D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/nuxi@3.0.0-rc.14/node_modules/nuxi/dist/chunks/prepare.mjs:30:18)
│   at async _main (/D:/Areas/Workspaces/GitHubRepos/tdcloud/node_modules/.pnpm/nuxi@3.0.0-rc.14/node_modules/nuxi/dist/cli.mjs:50:20)
└─ Failed in 2.2s
```
