### ISSUE TITLE
Illegal invocation

### ISSUE THREAD

**Issue by gertjanjansen** [nuxt-modules/web-vitals#77]
I just discovered that Vercel is injecting the package @nuxt/web-vitals into my Nuxt app, for speed insights: 

<img width="1077" alt="Screenshot 2023-12-07 at 14 51 10" src="https://github.com/nuxt-modules/web-vitals/assets/1429089/c86910a3-925f-471f-8340-a23604f0a4f0">

Their speed insight stats are great, but I get a lot of "Illegal invocation" errors as a result of this dependency:

```
TypeError: Illegal invocation
  at send(../../../node_modules/.pnpm/@nuxtjs+web-vitals@0.2.6/node_modules/@nuxtjs/web-vitals/dist/runtime/utils.mjs:29:15)
  at sendToAnalytics(../../../node_modules/.pnpm/@nuxtjs+web-vitals@0.2.6/node_modules/@nuxtjs/web-vitals/dist/runtime/providers/vercel.mjs:19:3)
  at e(../../../node_modules/.pnpm/@nuxtjs+web-vitals@0.2.6/node_modules/@nuxtjs/web-vitals/dist/runtime/web-vitals.mjs:10:25)
  at r(../../../node_modules/.pnpm/web-vitals@3.5.0/node_modules/web-vitals/dist/web-vitals.js:1:1114)
  at <anonymous>(../../../node_modules/.pnpm/web-vitals@3.5.0/node_modules/web-vitals/dist/web-vitals.js:1:6764)
  at sentryWrapped(../../../node_modules/.pnpm/@sentry+browser@7.85.0/node_modules/@sentry/browser/esm/helpers.js:90:17)
 ```

Any idea how to solve this?

Not sure if this is a bug in this module or on Vercel's side. I also posted it here, to be sure: https://github.com/orgs/vercel/discussions/5105

**Comment by danielroe** [comment]
Seems like it was fixed by Vercel.
